### ISSUE TITLE
Android - should have a different package structure

### ISSUE THREAD

**Issue by seladb** [PcapPlusPlus/new-packaging#22]
The existing package structure doesn't really fit Android. The way the package should be used is described here: https://github.com/seladb/ToyVpn-PcapPlusPlus

Basically, because an Android app is mostly Java/Kotlin code and (may) have some c++ code, it makes more sense to put the PcapPlusPlus libs under: `<APP_ROOT_FOLDER>/app/libs/pcapplusplus/<ARCH>/<API_VERSION>/`

For example: `ToyVpn-PcapPlusPlus/app/libs/pcapplusplus/arm64-v8a/30/`.

And the header files under: `<APP_ROOT_FOLDER>/app/libs/pcapplusplus/include`

The ]existing package](https://github.com/seladb/PcapPlusPlus/releases/download/v22.11/pcapplusplus-22.11-android.tar.gz) has this exact structure:
```text
|- pcapplusplus-22.11-android
  |- arm64-v8a
    |- 30
      |- libCommon++.a
      |- libPacket++.a
      |- libPcap++.a
  |- armeabi-v7a
    |- 30
      |- libCommon++.a
      |- libPacket++.a
      |- libPcap++.a
  |- x86
    |- 30
      |- libCommon++.a
      |- libPacket++.a
      |- libPcap++.a
  |- x86_64
    |- 30
      |- libCommon++.a
      |- libPacket++.a
      |- libPcap++.a
  |- include
    |- all .h files...
```

This makes it easy to use the package - all you need to do is copy the package content to `<APP_ROOT_FOLDER>/app/libs/` and rename `pcapplusplus-22.11-android` to `pcapplusplus` and your app should compile and run.

What we should do is create a similar structure for each arch:
```text
|- pcapplusplus-22.11+-android-<ARCH>-30
  |- <ARCH>
    |- 30
      |- libCommon++.a
      |- libPacket++.a
      |- libPcap++.a
```

This means we can remove the following folders:
- `/libs`
- `/example-app`
- `/libs/cmake`
- `/libs/pkgconfig`

**Comment by clementperon** [comment]
I have done a first version here https://github.com/clementperon/PcapPlusPlus/releases/tag/99.32.4

**Comment by seladb** [comment]
@clementperon maybe we can run all Android builds in parallel and then create another job to create the archive?

https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow

Something like:
```yaml
  android-build:
    strategy:
      matrix:
        target: [armeabi-v7a, x86, arm64-v8a, x86_64]
        api-version: 30

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout lipbcap for Android
        uses: actions/checkout@main
        with:
          repository: seladb/libpcap-android
          path: ./libpcap-android

      - name: Configure and Build PcapPlusPlus
        run: |
           ...

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ...
  
  android-package:

    runs-on: ubuntu-latest

    needs: android-build

    steps:
      - name: package
        run: tar ... 
```
